//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoVFTool.VFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VFUserInfo", Namespace="http://schemas.datacontract.org/2004/07/MSN.VirtualFile.Services.Model")]
    [System.SerializableAttribute()]
    public partial class VFUserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SubmitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] UserPrivilagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutoVFTool.VFService.UserRole[] UserRolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SubmitTime {
            get {
                return this.SubmitTimeField;
            }
            set {
                if ((this.SubmitTimeField.Equals(value) != true)) {
                    this.SubmitTimeField = value;
                    this.RaisePropertyChanged("SubmitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] UserPrivilages {
            get {
                return this.UserPrivilagesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPrivilagesField, value) != true)) {
                    this.UserPrivilagesField = value;
                    this.RaisePropertyChanged("UserPrivilages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutoVFTool.VFService.UserRole[] UserRoles {
            get {
                return this.UserRolesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRolesField, value) != true)) {
                    this.UserRolesField = value;
                    this.RaisePropertyChanged("UserRoles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRole", Namespace="http://schemas.datacontract.org/2004/07/MSN.VirtualFile.Services.Model")]
    [System.SerializableAttribute()]
    public partial class UserRole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentInfo", Namespace="http://schemas.datacontract.org/2004/07/MSN.VirtualFile.Services.Model")]
    [System.SerializableAttribute()]
    public partial class DocumentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChildCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutoVFTool.VFService.DocumentListInfo ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri ContentPageXSLTUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri ContentXSLTUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeleteActionPostXSLTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeleteActionUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DocumentLastPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentLastUpdaterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentLastUpdaterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentPUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DocumentSubmitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutoVFTool.VFService.DocumentType DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentXSLTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentXmlPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri ExportPageUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri FormTemplateUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewActionPostXSLTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewActionUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutoVFTool.VFService.DocumentInfo ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentDocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviewPathUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviewUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublishActionPostXSLTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublishActionUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchXSLTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri SearchXSLTUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateActionPostXSLTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateActionUriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChildCount {
            get {
                return this.ChildCountField;
            }
            set {
                if ((this.ChildCountField.Equals(value) != true)) {
                    this.ChildCountField = value;
                    this.RaisePropertyChanged("ChildCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutoVFTool.VFService.DocumentListInfo Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri ContentPageXSLTUri {
            get {
                return this.ContentPageXSLTUriField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentPageXSLTUriField, value) != true)) {
                    this.ContentPageXSLTUriField = value;
                    this.RaisePropertyChanged("ContentPageXSLTUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri ContentXSLTUri {
            get {
                return this.ContentXSLTUriField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentXSLTUriField, value) != true)) {
                    this.ContentXSLTUriField = value;
                    this.RaisePropertyChanged("ContentXSLTUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeleteActionPostXSLT {
            get {
                return this.DeleteActionPostXSLTField;
            }
            set {
                if ((object.ReferenceEquals(this.DeleteActionPostXSLTField, value) != true)) {
                    this.DeleteActionPostXSLTField = value;
                    this.RaisePropertyChanged("DeleteActionPostXSLT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeleteActionUri {
            get {
                return this.DeleteActionUriField;
            }
            set {
                if ((object.ReferenceEquals(this.DeleteActionUriField, value) != true)) {
                    this.DeleteActionUriField = value;
                    this.RaisePropertyChanged("DeleteActionUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentDescription {
            get {
                return this.DocumentDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentDescriptionField, value) != true)) {
                    this.DocumentDescriptionField = value;
                    this.RaisePropertyChanged("DocumentDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentExtension {
            get {
                return this.DocumentExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentExtensionField, value) != true)) {
                    this.DocumentExtensionField = value;
                    this.RaisePropertyChanged("DocumentExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DocumentLastPublished {
            get {
                return this.DocumentLastPublishedField;
            }
            set {
                if ((this.DocumentLastPublishedField.Equals(value) != true)) {
                    this.DocumentLastPublishedField = value;
                    this.RaisePropertyChanged("DocumentLastPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentLastUpdater {
            get {
                return this.DocumentLastUpdaterField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentLastUpdaterField, value) != true)) {
                    this.DocumentLastUpdaterField = value;
                    this.RaisePropertyChanged("DocumentLastUpdater");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentLastUpdaterID {
            get {
                return this.DocumentLastUpdaterIDField;
            }
            set {
                if ((this.DocumentLastUpdaterIDField.Equals(value) != true)) {
                    this.DocumentLastUpdaterIDField = value;
                    this.RaisePropertyChanged("DocumentLastUpdaterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentPUID {
            get {
                return this.DocumentPUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentPUIDField, value) != true)) {
                    this.DocumentPUIDField = value;
                    this.RaisePropertyChanged("DocumentPUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentPath {
            get {
                return this.DocumentPathField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentPathField, value) != true)) {
                    this.DocumentPathField = value;
                    this.RaisePropertyChanged("DocumentPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DocumentSubmitTime {
            get {
                return this.DocumentSubmitTimeField;
            }
            set {
                if ((this.DocumentSubmitTimeField.Equals(value) != true)) {
                    this.DocumentSubmitTimeField = value;
                    this.RaisePropertyChanged("DocumentSubmitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentTitle {
            get {
                return this.DocumentTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTitleField, value) != true)) {
                    this.DocumentTitleField = value;
                    this.RaisePropertyChanged("DocumentTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutoVFTool.VFService.DocumentType DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((this.DocumentTypeField.Equals(value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentXSLT {
            get {
                return this.DocumentXSLTField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentXSLTField, value) != true)) {
                    this.DocumentXSLTField = value;
                    this.RaisePropertyChanged("DocumentXSLT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentXmlPath {
            get {
                return this.DocumentXmlPathField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentXmlPathField, value) != true)) {
                    this.DocumentXmlPathField = value;
                    this.RaisePropertyChanged("DocumentXmlPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri ExportPageUri {
            get {
                return this.ExportPageUriField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportPageUriField, value) != true)) {
                    this.ExportPageUriField = value;
                    this.RaisePropertyChanged("ExportPageUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri FormTemplateUri {
            get {
                return this.FormTemplateUriField;
            }
            set {
                if ((object.ReferenceEquals(this.FormTemplateUriField, value) != true)) {
                    this.FormTemplateUriField = value;
                    this.RaisePropertyChanged("FormTemplateUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewActionPostXSLT {
            get {
                return this.NewActionPostXSLTField;
            }
            set {
                if ((object.ReferenceEquals(this.NewActionPostXSLTField, value) != true)) {
                    this.NewActionPostXSLTField = value;
                    this.RaisePropertyChanged("NewActionPostXSLT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewActionUri {
            get {
                return this.NewActionUriField;
            }
            set {
                if ((object.ReferenceEquals(this.NewActionUriField, value) != true)) {
                    this.NewActionUriField = value;
                    this.RaisePropertyChanged("NewActionUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputUri {
            get {
                return this.OutputUriField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputUriField, value) != true)) {
                    this.OutputUriField = value;
                    this.RaisePropertyChanged("OutputUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutoVFTool.VFService.DocumentInfo Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentDocumentID {
            get {
                return this.ParentDocumentIDField;
            }
            set {
                if ((this.ParentDocumentIDField.Equals(value) != true)) {
                    this.ParentDocumentIDField = value;
                    this.RaisePropertyChanged("ParentDocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviewPathUri {
            get {
                return this.PreviewPathUriField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviewPathUriField, value) != true)) {
                    this.PreviewPathUriField = value;
                    this.RaisePropertyChanged("PreviewPathUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviewUri {
            get {
                return this.PreviewUriField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviewUriField, value) != true)) {
                    this.PreviewUriField = value;
                    this.RaisePropertyChanged("PreviewUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublishActionPostXSLT {
            get {
                return this.PublishActionPostXSLTField;
            }
            set {
                if ((object.ReferenceEquals(this.PublishActionPostXSLTField, value) != true)) {
                    this.PublishActionPostXSLTField = value;
                    this.RaisePropertyChanged("PublishActionPostXSLT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublishActionUri {
            get {
                return this.PublishActionUriField;
            }
            set {
                if ((object.ReferenceEquals(this.PublishActionUriField, value) != true)) {
                    this.PublishActionUriField = value;
                    this.RaisePropertyChanged("PublishActionUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchXSLT {
            get {
                return this.SearchXSLTField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchXSLTField, value) != true)) {
                    this.SearchXSLTField = value;
                    this.RaisePropertyChanged("SearchXSLT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri SearchXSLTUri {
            get {
                return this.SearchXSLTUriField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchXSLTUriField, value) != true)) {
                    this.SearchXSLTUriField = value;
                    this.RaisePropertyChanged("SearchXSLTUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateActionPostXSLT {
            get {
                return this.UpdateActionPostXSLTField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateActionPostXSLTField, value) != true)) {
                    this.UpdateActionPostXSLTField = value;
                    this.RaisePropertyChanged("UpdateActionPostXSLT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateActionUri {
            get {
                return this.UpdateActionUriField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateActionUriField, value) != true)) {
                    this.UpdateActionUriField = value;
                    this.RaisePropertyChanged("UpdateActionUri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DocumentListInfo", Namespace="http://schemas.datacontract.org/2004/07/MSN.VirtualFile.Services.Model", ItemName="DocumentInfo")]
    [System.SerializableAttribute()]
    public class DocumentListInfo : System.Collections.Generic.List<AutoVFTool.VFService.DocumentInfo> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentType", Namespace="http://schemas.datacontract.org/2004/07/MSN.VirtualFile.Services.Model")]
    public enum DocumentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Site = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Folder = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Page = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Content = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Loading = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentInfo", Namespace="http://schemas.datacontract.org/2004/07/MSN.VirtualFile.Services.Model")]
    [System.SerializableAttribute()]
    public partial class ContentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ContentFirstPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentInputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ContentLastPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContentLastUpdaterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentLastUpdaterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentOutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentPUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ContentRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ContentSubmitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ContentVoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentXmlPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewActionResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputPhysicPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviewPathUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviewUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublishActionResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateActionResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentDescription {
            get {
                return this.ContentDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentDescriptionField, value) != true)) {
                    this.ContentDescriptionField = value;
                    this.RaisePropertyChanged("ContentDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentExtension {
            get {
                return this.ContentExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentExtensionField, value) != true)) {
                    this.ContentExtensionField = value;
                    this.RaisePropertyChanged("ContentExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ContentFirstPublished {
            get {
                return this.ContentFirstPublishedField;
            }
            set {
                if ((this.ContentFirstPublishedField.Equals(value) != true)) {
                    this.ContentFirstPublishedField = value;
                    this.RaisePropertyChanged("ContentFirstPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContentID {
            get {
                return this.ContentIDField;
            }
            set {
                if ((this.ContentIDField.Equals(value) != true)) {
                    this.ContentIDField = value;
                    this.RaisePropertyChanged("ContentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentInput {
            get {
                return this.ContentInputField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentInputField, value) != true)) {
                    this.ContentInputField = value;
                    this.RaisePropertyChanged("ContentInput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ContentLastPublished {
            get {
                return this.ContentLastPublishedField;
            }
            set {
                if ((this.ContentLastPublishedField.Equals(value) != true)) {
                    this.ContentLastPublishedField = value;
                    this.RaisePropertyChanged("ContentLastPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContentLastUpdaterID {
            get {
                return this.ContentLastUpdaterIDField;
            }
            set {
                if ((this.ContentLastUpdaterIDField.Equals(value) != true)) {
                    this.ContentLastUpdaterIDField = value;
                    this.RaisePropertyChanged("ContentLastUpdaterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentLastUpdaterName {
            get {
                return this.ContentLastUpdaterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentLastUpdaterNameField, value) != true)) {
                    this.ContentLastUpdaterNameField = value;
                    this.RaisePropertyChanged("ContentLastUpdaterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentOutput {
            get {
                return this.ContentOutputField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentOutputField, value) != true)) {
                    this.ContentOutputField = value;
                    this.RaisePropertyChanged("ContentOutput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentPUID {
            get {
                return this.ContentPUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentPUIDField, value) != true)) {
                    this.ContentPUIDField = value;
                    this.RaisePropertyChanged("ContentPUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentPath {
            get {
                return this.ContentPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentPathField, value) != true)) {
                    this.ContentPathField = value;
                    this.RaisePropertyChanged("ContentPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ContentRating {
            get {
                return this.ContentRatingField;
            }
            set {
                if ((this.ContentRatingField.Equals(value) != true)) {
                    this.ContentRatingField = value;
                    this.RaisePropertyChanged("ContentRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ContentSubmitTime {
            get {
                return this.ContentSubmitTimeField;
            }
            set {
                if ((this.ContentSubmitTimeField.Equals(value) != true)) {
                    this.ContentSubmitTimeField = value;
                    this.RaisePropertyChanged("ContentSubmitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentTitle {
            get {
                return this.ContentTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTitleField, value) != true)) {
                    this.ContentTitleField = value;
                    this.RaisePropertyChanged("ContentTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ContentVote {
            get {
                return this.ContentVoteField;
            }
            set {
                if ((this.ContentVoteField.Equals(value) != true)) {
                    this.ContentVoteField = value;
                    this.RaisePropertyChanged("ContentVote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentXmlPath {
            get {
                return this.ContentXmlPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentXmlPathField, value) != true)) {
                    this.ContentXmlPathField = value;
                    this.RaisePropertyChanged("ContentXmlPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewActionResponse {
            get {
                return this.NewActionResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.NewActionResponseField, value) != true)) {
                    this.NewActionResponseField = value;
                    this.RaisePropertyChanged("NewActionResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputPhysicPath {
            get {
                return this.OutputPhysicPathField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputPhysicPathField, value) != true)) {
                    this.OutputPhysicPathField = value;
                    this.RaisePropertyChanged("OutputPhysicPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputUri {
            get {
                return this.OutputUriField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputUriField, value) != true)) {
                    this.OutputUriField = value;
                    this.RaisePropertyChanged("OutputUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviewPathUri {
            get {
                return this.PreviewPathUriField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviewPathUriField, value) != true)) {
                    this.PreviewPathUriField = value;
                    this.RaisePropertyChanged("PreviewPathUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviewUri {
            get {
                return this.PreviewUriField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviewUriField, value) != true)) {
                    this.PreviewUriField = value;
                    this.RaisePropertyChanged("PreviewUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublishActionResponse {
            get {
                return this.PublishActionResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.PublishActionResponseField, value) != true)) {
                    this.PublishActionResponseField = value;
                    this.RaisePropertyChanged("PublishActionResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequenceID {
            get {
                return this.SequenceIDField;
            }
            set {
                if ((this.SequenceIDField.Equals(value) != true)) {
                    this.SequenceIDField = value;
                    this.RaisePropertyChanged("SequenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateActionResponse {
            get {
                return this.UpdateActionResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateActionResponseField, value) != true)) {
                    this.UpdateActionResponseField = value;
                    this.RaisePropertyChanged("UpdateActionResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ContentListInfo", Namespace="http://schemas.datacontract.org/2004/07/MSN.VirtualFile.Services.Model", ItemName="ContentInfo")]
    [System.SerializableAttribute()]
    public class ContentListInfo : System.Collections.Generic.List<AutoVFTool.VFService.ContentInfo> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientFileInfo", Namespace="http://schemas.datacontract.org/2004/07/MSN.VirtualFile.Services.Model")]
    [System.SerializableAttribute()]
    public partial class ClientFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BytesUploadedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileMetadataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutoVFTool.VFService.FileStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] StreamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlockID {
            get {
                return this.BlockIDField;
            }
            set {
                if ((this.BlockIDField.Equals(value) != true)) {
                    this.BlockIDField = value;
                    this.RaisePropertyChanged("BlockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BytesUploaded {
            get {
                return this.BytesUploadedField;
            }
            set {
                if ((this.BytesUploadedField.Equals(value) != true)) {
                    this.BytesUploadedField = value;
                    this.RaisePropertyChanged("BytesUploaded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileMetadata {
            get {
                return this.FileMetadataField;
            }
            set {
                if ((object.ReferenceEquals(this.FileMetadataField, value) != true)) {
                    this.FileMetadataField = value;
                    this.RaisePropertyChanged("FileMetadata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((this.SessionIDField.Equals(value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutoVFTool.VFService.FileStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Stream {
            get {
                return this.StreamField;
            }
            set {
                if ((object.ReferenceEquals(this.StreamField, value) != true)) {
                    this.StreamField = value;
                    this.RaisePropertyChanged("Stream");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileStatus", Namespace="http://schemas.datacontract.org/2004/07/MSN.VirtualFile.Services.Model")]
    public enum FileStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uploading = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finished = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Removed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostCompleted = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteFileInfo", Namespace="http://schemas.datacontract.org/2004/07/MSN.VirtualFile.Services.Model")]
    [System.SerializableAttribute()]
    public partial class RemoteFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri LiveUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutoVFTool.VFService.FileStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri LiveUri {
            get {
                return this.LiveUriField;
            }
            set {
                if ((object.ReferenceEquals(this.LiveUriField, value) != true)) {
                    this.LiveUriField = value;
                    this.RaisePropertyChanged("LiveUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((this.SessionIDField.Equals(value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutoVFTool.VFService.FileStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://virtualfile.msn.com", ConfigurationName="VFService.IPSPService")]
    public interface IPSPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/LoginStatus", ReplyAction="http://virtualfile.msn.com/IPSPService/LoginStatusResponse")]
        AutoVFTool.VFService.VFUserInfo LoginStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/AddDocument", ReplyAction="http://virtualfile.msn.com/IPSPService/AddDocumentResponse")]
        AutoVFTool.VFService.DocumentInfo AddDocument(AutoVFTool.VFService.DocumentInfo document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/EditDocument", ReplyAction="http://virtualfile.msn.com/IPSPService/EditDocumentResponse")]
        AutoVFTool.VFService.DocumentInfo EditDocument(AutoVFTool.VFService.DocumentInfo document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/GetDocument", ReplyAction="http://virtualfile.msn.com/IPSPService/GetDocumentResponse")]
        AutoVFTool.VFService.DocumentInfo GetDocument(int documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/DeleteDocument", ReplyAction="http://virtualfile.msn.com/IPSPService/DeleteDocumentResponse")]
        bool DeleteDocument(int documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/GetDocumentList", ReplyAction="http://virtualfile.msn.com/IPSPService/GetDocumentListResponse")]
        AutoVFTool.VFService.DocumentListInfo GetDocumentList(int parentDocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/GetDocumentListByPath", ReplyAction="http://virtualfile.msn.com/IPSPService/GetDocumentListByPathResponse")]
        AutoVFTool.VFService.DocumentListInfo GetDocumentListByPath(string parentDocumentPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/PublishPage", ReplyAction="http://virtualfile.msn.com/IPSPService/PublishPageResponse")]
        System.Uri PublishPage(int documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/AddContent", ReplyAction="http://virtualfile.msn.com/IPSPService/AddContentResponse")]
        AutoVFTool.VFService.ContentInfo AddContent(AutoVFTool.VFService.ContentInfo content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/EditContent", ReplyAction="http://virtualfile.msn.com/IPSPService/EditContentResponse")]
        AutoVFTool.VFService.ContentInfo EditContent(AutoVFTool.VFService.ContentInfo content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/DeleteContent", ReplyAction="http://virtualfile.msn.com/IPSPService/DeleteContentResponse")]
        bool DeleteContent(int contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/GetContent", ReplyAction="http://virtualfile.msn.com/IPSPService/GetContentResponse")]
        AutoVFTool.VFService.ContentInfo GetContent(int contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/CopyContentToPage", ReplyAction="http://virtualfile.msn.com/IPSPService/CopyContentToPageResponse")]
        AutoVFTool.VFService.ContentInfo CopyContentToPage(int contentID, int documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/PublishContent", ReplyAction="http://virtualfile.msn.com/IPSPService/PublishContentResponse")]
        AutoVFTool.VFService.ContentInfo PublishContent(int contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/GetContentList", ReplyAction="http://virtualfile.msn.com/IPSPService/GetContentListResponse")]
        AutoVFTool.VFService.ContentListInfo GetContentList(int parentDocumentID, int pageIndex, int pageSize, string contentTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/MoveContent", ReplyAction="http://virtualfile.msn.com/IPSPService/MoveContentResponse")]
        bool MoveContent(int contentID, int sequenceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/ExportContentsFromPage", ReplyAction="http://virtualfile.msn.com/IPSPService/ExportContentsFromPageResponse")]
        System.IO.Stream ExportContentsFromPage(string documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/ImportContentToPage", ReplyAction="http://virtualfile.msn.com/IPSPService/ImportContentToPageResponse")]
        AutoVFTool.VFService.ContentInfo ImportContentToPage(AutoVFTool.VFService.ContentInfo content, bool overwrite, bool publish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/UploadImage", ReplyAction="http://virtualfile.msn.com/IPSPService/UploadImageResponse")]
        AutoVFTool.VFService.RemoteFileInfo UploadImage(AutoVFTool.VFService.ClientFileInfo file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/UploadImageWithUrl", ReplyAction="http://virtualfile.msn.com/IPSPService/UploadImageWithUrlResponse")]
        System.Uri UploadImageWithUrl(string documentPath, System.Uri imageUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IPSPService/GetContentFormTemplate", ReplyAction="http://virtualfile.msn.com/IPSPService/GetContentFormTemplateResponse")]
        string GetContentFormTemplate(int documentID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPSPServiceChannel : AutoVFTool.VFService.IPSPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PSPServiceClient : System.ServiceModel.ClientBase<AutoVFTool.VFService.IPSPService>, AutoVFTool.VFService.IPSPService {
        
        public PSPServiceClient() {
        }
        
        public PSPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PSPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AutoVFTool.VFService.VFUserInfo LoginStatus() {
            return base.Channel.LoginStatus();
        }
        
        public AutoVFTool.VFService.DocumentInfo AddDocument(AutoVFTool.VFService.DocumentInfo document) {
            return base.Channel.AddDocument(document);
        }
        
        public AutoVFTool.VFService.DocumentInfo EditDocument(AutoVFTool.VFService.DocumentInfo document) {
            return base.Channel.EditDocument(document);
        }
        
        public AutoVFTool.VFService.DocumentInfo GetDocument(int documentID) {
            return base.Channel.GetDocument(documentID);
        }
        
        public bool DeleteDocument(int documentID) {
            return base.Channel.DeleteDocument(documentID);
        }
        
        public AutoVFTool.VFService.DocumentListInfo GetDocumentList(int parentDocumentID) {
            return base.Channel.GetDocumentList(parentDocumentID);
        }
        
        public AutoVFTool.VFService.DocumentListInfo GetDocumentListByPath(string parentDocumentPath) {
            return base.Channel.GetDocumentListByPath(parentDocumentPath);
        }
        
        public System.Uri PublishPage(int documentID) {
            return base.Channel.PublishPage(documentID);
        }
        
        public AutoVFTool.VFService.ContentInfo AddContent(AutoVFTool.VFService.ContentInfo content) {
            return base.Channel.AddContent(content);
        }
        
        public AutoVFTool.VFService.ContentInfo EditContent(AutoVFTool.VFService.ContentInfo content) {
            return base.Channel.EditContent(content);
        }
        
        public bool DeleteContent(int contentID) {
            return base.Channel.DeleteContent(contentID);
        }
        
        public AutoVFTool.VFService.ContentInfo GetContent(int contentID) {
            return base.Channel.GetContent(contentID);
        }
        
        public AutoVFTool.VFService.ContentInfo CopyContentToPage(int contentID, int documentID) {
            return base.Channel.CopyContentToPage(contentID, documentID);
        }
        
        public AutoVFTool.VFService.ContentInfo PublishContent(int contentID) {
            return base.Channel.PublishContent(contentID);
        }
        
        public AutoVFTool.VFService.ContentListInfo GetContentList(int parentDocumentID, int pageIndex, int pageSize, string contentTitle) {
            return base.Channel.GetContentList(parentDocumentID, pageIndex, pageSize, contentTitle);
        }
        
        public bool MoveContent(int contentID, int sequenceID) {
            return base.Channel.MoveContent(contentID, sequenceID);
        }
        
        public System.IO.Stream ExportContentsFromPage(string documentID) {
            return base.Channel.ExportContentsFromPage(documentID);
        }
        
        public AutoVFTool.VFService.ContentInfo ImportContentToPage(AutoVFTool.VFService.ContentInfo content, bool overwrite, bool publish) {
            return base.Channel.ImportContentToPage(content, overwrite, publish);
        }
        
        public AutoVFTool.VFService.RemoteFileInfo UploadImage(AutoVFTool.VFService.ClientFileInfo file) {
            return base.Channel.UploadImage(file);
        }
        
        public System.Uri UploadImageWithUrl(string documentPath, System.Uri imageUrl) {
            return base.Channel.UploadImageWithUrl(documentPath, imageUrl);
        }
        
        public string GetContentFormTemplate(int documentID) {
            return base.Channel.GetContentFormTemplate(documentID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://virtualfile.msn.com", ConfigurationName="VFService.IXMLPSPService")]
    public interface IXMLPSPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/XmlGetPageOutput", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/XmlGetPageOutputResponse")]
        System.Xml.Linq.XElement XmlGetPageOutput(string documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/XmlGetPageOutputByPath", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/XmlGetPageOutputByPathResponse")]
        System.Xml.Linq.XElement XmlGetPageOutputByPath(string documentPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/XmlGetContentOutput", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/XmlGetContentOutputResponse")]
        System.Xml.Linq.XElement XmlGetContentOutput(string contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/XmlGetContentOutputByPath", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/XmlGetContentOutputByPathResponse")]
        System.Xml.Linq.XElement XmlGetContentOutputByPath(string contentPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/XmlGetOutputByPath", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/XmlGetOutputByPathResponse")]
        System.Xml.Linq.XElement XmlGetOutputByPath(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/XmlGetContentFormTemplate", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/XmlGetContentFormTemplateResponse")]
        System.Xml.Linq.XElement XmlGetContentFormTemplate(string documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/GetContentXSLT", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/GetContentXSLTResponse")]
        System.Xml.Linq.XElement GetContentXSLT(string documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/GetContentPageXSLT", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/GetContentPageXSLTResponse")]
        System.Xml.Linq.XElement GetContentPageXSLT(string documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/GetSearchXSLT", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/GetSearchXSLTResponse")]
        System.Xml.Linq.XElement GetSearchXSLT(string documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/XmlExportContentsFromPage", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/XmlExportContentsFromPageResponse")]
        System.IO.Stream XmlExportContentsFromPage(string documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://virtualfile.msn.com/IXMLPSPService/ResetContentSequence", ReplyAction="http://virtualfile.msn.com/IXMLPSPService/ResetContentSequenceResponse")]
        bool ResetContentSequence(string documentID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXMLPSPServiceChannel : AutoVFTool.VFService.IXMLPSPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XMLPSPServiceClient : System.ServiceModel.ClientBase<AutoVFTool.VFService.IXMLPSPService>, AutoVFTool.VFService.IXMLPSPService {
        
        public XMLPSPServiceClient() {
        }
        
        public XMLPSPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XMLPSPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLPSPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLPSPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.Linq.XElement XmlGetPageOutput(string documentID) {
            return base.Channel.XmlGetPageOutput(documentID);
        }
        
        public System.Xml.Linq.XElement XmlGetPageOutputByPath(string documentPath) {
            return base.Channel.XmlGetPageOutputByPath(documentPath);
        }
        
        public System.Xml.Linq.XElement XmlGetContentOutput(string contentID) {
            return base.Channel.XmlGetContentOutput(contentID);
        }
        
        public System.Xml.Linq.XElement XmlGetContentOutputByPath(string contentPath) {
            return base.Channel.XmlGetContentOutputByPath(contentPath);
        }
        
        public System.Xml.Linq.XElement XmlGetOutputByPath(string path) {
            return base.Channel.XmlGetOutputByPath(path);
        }
        
        public System.Xml.Linq.XElement XmlGetContentFormTemplate(string documentID) {
            return base.Channel.XmlGetContentFormTemplate(documentID);
        }
        
        public System.Xml.Linq.XElement GetContentXSLT(string documentID) {
            return base.Channel.GetContentXSLT(documentID);
        }
        
        public System.Xml.Linq.XElement GetContentPageXSLT(string documentID) {
            return base.Channel.GetContentPageXSLT(documentID);
        }
        
        public System.Xml.Linq.XElement GetSearchXSLT(string documentID) {
            return base.Channel.GetSearchXSLT(documentID);
        }
        
        public System.IO.Stream XmlExportContentsFromPage(string documentID) {
            return base.Channel.XmlExportContentsFromPage(documentID);
        }
        
        public bool ResetContentSequence(string documentID) {
            return base.Channel.ResetContentSequence(documentID);
        }
    }
}
